In [3]:
import open3d as o3d
import numpy as np
import torch

points = np.random.rand(1000, 3)

points_tensor = points  # 这里替换为你的点云数据tensor

# 假设你的tensor变量名为 points_tensor
# 将tensor转换为numpy数组，然后创建Open3D点云对象
if hasattr(points_tensor, 'cpu'):  # PyTorch tensor
    points_array = points_tensor.cpu().detach().numpy()
elif hasattr(points_tensor, 'numpy'):  # TensorFlow tensor
    points_array = points_tensor.numpy()
else:  # 已经是numpy数组
    points_array = points_tensor

# 创建Open3D点云对象
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points_array)

# 3. 计算法向量（ISS算法需要）
pcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)
)

# 4. 配置ISS参数
iss_keypoints = o3d.geometry.keypoint.compute_iss_keypoints(
    pcd,
    salient_radius=0.1,      # 显著性半径
    non_max_radius=0.05,     # 非最大值抑制半径
    gamma_21=0.975,          # 第二和第一特征值比值阈值
    gamma_32=0.975,          # 第三和第二特征值比值阈值
    min_neighbors=5          # 最小邻居数
)

# 5. 可视化结果
print(f"检测到 {len(iss_keypoints.points)} 个ISS关键点")

# 输出关键点的位置坐标
keypoints_array = np.asarray(iss_keypoints.points)
print("ISS关键点坐标:")
for i, point in enumerate(keypoints_array):
    print(f"关键点 {i+1}: ({point[0]:.4f}, {point[1]:.4f}, {point[2]:.4f})")

# 给关键点上色（红色）
iss_keypoints.paint_uniform_color([1, 0, 0])

# 给原始点云上色（灰色）
pcd.paint_uniform_color([0.5, 0.5, 0.5])

# 显示结果
o3d.visualization.draw_geometries([pcd, iss_keypoints],
                                window_name="ISS关键点检测结果")

检测到 0 个ISS关键点
ISS关键点坐标:
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.


In [2]:
# 生成一批 100 * 1024 * 3 的随机torch tensor数据
import torch
import numpy as np
from pointNN import Point_NN

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

def generate_random_tensors(num_tensors=100, tensor_size=(1024, 3)):
    """
    生成指定数量的随机torch tensor数据。

    参数:
    num_tensors (int): 要生成的tensor数量，默认为100。
    tensor_size (tuple): 每个tensor的大小，默认为(1024, 3)。

    返回:
    list: 包含生成的tensor的列表。
    """
    tensors = []
    for _ in range(num_tensors):
        tensor = torch.tensor(np.random.rand(*tensor_size), dtype=torch.float32)
        tensors.append(tensor)
    return tensors

points = generate_random_tensors(1, (50000, 3))
# 将points转换为一个torch tensor
points = torch.stack(points, dim=0)  # shape: (100, 1024, 3)

# 检查可用的GPU并选择空闲的GPU

def get_free_gpu():
    """
    获取显存使用最少的GPU设备
    """
    if not torch.cuda.is_available():
        return torch.device('cpu')
    
    num_gpus = torch.cuda.device_count()
    if num_gpus == 1:
        return torch.device('cuda:0')
    
    # 检查每个GPU的显存使用情况
    min_memory_used = float('inf')
    best_gpu = 0
    
    for i in range(num_gpus):
        torch.cuda.set_device(i)
        memory_used = torch.cuda.memory_allocated(i)
        if memory_used < min_memory_used:
            min_memory_used = memory_used
            best_gpu = i
    
    return torch.device(f'cuda:{best_gpu}')

# 获取最佳GPU设备
device = get_free_gpu()
print(f"使用设备: {device}")
torch.cuda.set_device(device)


points = points.cuda().permute(0, 2, 1)

point_nn = Point_NN(input_points=44517, num_stages=4,
                    embed_dim=72, k_neighbors=90,
                    alpha=1000, beta=100).cuda()
point_nn.eval()

# 计算下面这段代码的运行时间
import time
import torch
start_time = time.time()
point_features = point_nn(points)
end_time = time.time()
print(f"运行时间: {end_time - start_time} 秒")

print(f"point_features shape: {point_features.shape}")  # 输出特征的形状



使用设备: cuda:1
Raw-point embedding shape: torch.Size([1, 72, 50000])
Local center points shape: torch.Size([1, 22258, 3]), Local center features shape: torch.Size([1, 22258, 72])
k-NN index shape: torch.Size([1, 22258, 90])
Stage 1 output shape: torch.Size([1, 144, 22258])
Local center points shape: torch.Size([1, 11129, 3]), Local center features shape: torch.Size([1, 11129, 144])
k-NN index shape: torch.Size([1, 11129, 90])
Stage 2 output shape: torch.Size([1, 288, 11129])
Local center points shape: torch.Size([1, 5564, 3]), Local center features shape: torch.Size([1, 5564, 288])
k-NN index shape: torch.Size([1, 5564, 90])
Stage 3 output shape: torch.Size([1, 576, 5564])
Local center points shape: torch.Size([1, 2782, 3]), Local center features shape: torch.Size([1, 2782, 576])
k-NN index shape: torch.Size([1, 2782, 90])
Stage 4 output shape: torch.Size([1, 1152, 2782])
运行时间: 2.7766082286834717 秒
point_features shape: torch.Size([1, 1152])


In [7]:
import torch
def get_free_gpu():
    """
    获取显存使用最少的GPU设备
    """
    if not torch.cuda.is_available():
        return torch.device('cpu')
    
    num_gpus = torch.cuda.device_count()
    print(f"可用GPU数量: {num_gpus}")
    if num_gpus == 1:
        return torch.device('cuda:0')
    
    # 检查每个GPU的显存使用情况
    min_memory_used = float('inf')
    best_gpu = 0
    
    for i in range(num_gpus):
        torch.cuda.set_device(i)
        memory_used = torch.cuda.memory_allocated(i)
        print(f"GPU {i} 显存使用: {memory_used / (1024 ** 2):.2f} MB")
        if memory_used <= min_memory_used:
            min_memory_used = memory_used
            best_gpu = i
    
    return torch.device(f'cuda:{best_gpu}')

# 获取最佳GPU设备
device = get_free_gpu()
print(f"使用设备: {device}")

可用GPU数量: 4
GPU 0 显存使用: 0.00 MB
GPU 1 显存使用: 0.00 MB
GPU 2 显存使用: 0.00 MB
GPU 3 显存使用: 0.00 MB
使用设备: cuda:3


In [ ]:
# 模式识别作业 No.4
import numpy as np

# ----------------------------
# 1. 定义样本数据
# ----------------------------

class1_samples = [
    np.array([0, 0, 0]),
    np.array([1, 0, 0]),
    np.array([1, 0, 1]),
    np.array([1, 1, 0]),
]

class2_samples = [
    np.array([0, 0, 1]),
    np.array([0, 1, 0]),
    np.array([0, 1, 1]),
    np.array([1, 1, 1]),
]

# ----------------------------
# 2. 计算类均值向量
# ----------------------------

mu1 = np.mean(class1_samples, axis=0)
mu2 = np.mean(class2_samples, axis=0)

# ----------------------------
# 3. 计算总均值向量
# ----------------------------

total_samples = np.vstack(class1_samples + class2_samples)
mu_total = np.mean(total_samples, axis=0)

# ----------------------------
# 4. 计算类内散度矩阵 S_W1, S_W2
# ----------------------------

def compute_sw(samples, mu_class):
    sw = np.zeros((3, 3))
    for x in samples:
        diff = x - mu_class
        sw += np.outer(diff, diff)
    return sw

S_W1 = compute_sw(class1_samples, mu1)
S_W2 = compute_sw(class2_samples, mu2)
S_W = S_W1 + S_W2

# ----------------------------
# 5. 计算类间散度矩阵 S_B
# ----------------------------

N1 = len(class1_samples)
N2 = len(class2_samples)

mu_diff1 = mu1 - mu_total
mu_diff2 = mu2 - mu_total

S_B = N1 * np.outer(mu_diff1, mu_diff1) + N2 * np.outer(mu_diff2, mu_diff2)

# ----------------------------
# 6. 求解广义特征值问题 S_B w = λ S_W w
# ----------------------------

# 使用 numpy.linalg.eigh 保证矩阵对称性
SW_inv = np.linalg.inv(S_W)
SW_inv_SB = SW_inv @ S_B

# 解广义特征值问题
eigenvalues, eigenvectors = np.linalg.eigh(SW_inv_SB)

# ----------------------------
# 7. 输出结果
# ----------------------------

print("类内散度矩阵 S_W:")
print(S_W)
print("\n类间散度矩阵 S_B:")
print(S_B)
print("\n特征值 (λ):")
print(eigenvalues)
print("\n特征向量 (w):")
print(eigenvectors)

类内散度矩阵 S_W:
[[ 1.5  0.5  0.5]
 [ 0.5  1.5 -0.5]
 [ 0.5 -0.5  1.5]]

类间散度矩阵 S_B:
[[ 0.5 -0.5 -0.5]
 [-0.5  0.5  0.5]
 [-0.5  0.5  0.5]]

特征值 (λ):
[-4.51979064e-16 -1.58314883e-17  3.00000000e+00]

特征向量 (w):
[[ 0.80907772 -0.10981765  0.57735027]
 [ 0.49964373  0.64577303 -0.57735027]
 [ 0.30943399 -0.75559068 -0.57735027]]
